
server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-example?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-handlers-package: com.yangtao.handler


